# This is a basic workflow to help you get started with Actions

name: CI
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            version:
              - '1.6'
              - '1' # expands to lates 1.x.y release
              - nightly
              - '~1.9.0-0' # temporarily test on beta and rc version of 1.9
            os: 
              - ubuntu-latest
              - windows-latest
              - macOS-latest
        
        steps:
            - name: Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: ${{ matrix.version }}
            - name: Install R
              uses: r-lib/actions/setup-r@v2
            - name: Add RHOME to LD_LIBRARY_PATH
              run: echo "LD_LIBRARY_PATH=$(R RHOME)/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
              if: matrix.os == 'ubuntu-latest'
            - name: Install R packages
              shell: Rscript {0}
              run: |
                install.packages("nets")
            - name: Test RCall
              shell: julia --color=yes --project=. {0}
              run: |
                using Pkg
                Pkg.add("RCall")
                using RCall
                R"""library("nets")"""